#!/bin/bash
#
# selects and displays a random background, copies it as png to /tmp for i3lock
#
# args: none

prev_file="${HOME}/.cache/prev_wallpaper"
prev="$(< ${prev_file})"
wallpaper="$(find ${HOME}/media/pictures/wallpapers/ -type f ! -name ${prev:-none} | \
                  sort -R | tail -n 1)"
echo "$(basename ${wallpaper})" > "${prev_file}"

dimension="$(xrandr --current | awk '/ primary/{print substr($4, 0, 9)}')"
magick "${wallpaper}" -scale "${dimension}"\! /tmp/background.png
feh --no-fehbg --bg-fill /tmp/background.png
