#!/bin/bash
#
# selects and displays a random background
#
# args: none

randBackground="$(find ${HOME}/media/pictures/wallpapers/ -type f | sort -R | tail -n 1)"
feh --no-fehbg --bg-fill "${randBackground}"
